"""
Compress www/index.html and emit it as a C array for the firmware to serve.

Why this exists as a PlatformIO pre-build hook rather than a CMake rule:

  * EMBED_FILES generates an assembly stub through a CMake custom command.
    PlatformIO drives the ESP-IDF build through its own layer that never runs
    those commands, so the build then fails on a file nobody produced.
  * Generating at CMake *configure* time works, but PlatformIO does not re-run
    configure when an unrelated source file changes. CMAKE_CONFIGURE_DEPENDS did
    not help. The result was worse than a build error: every build succeeded
    while the firmware kept serving a stale page.

A pre-build hook runs on every build, so the embedded copy cannot drift from the
source again.

Copyright 2026 Jonas Brüstel
SPDX-License-Identifier: Apache-2.0
"""

import gzip
import pathlib
import shutil
import subprocess

Import("env")  # noqa: F821  (injected by PlatformIO)

ROOT = pathlib.Path(env.subst("$PROJECT_DIR"))  # noqa: F821
SRC = ROOT / "www" / "index.html"
OUT = ROOT / "components" / "app_web" / "src" / "ui_asset.c"


def generate():
    if not SRC.is_file():
        raise SystemExit(f"gen_ui_asset: {SRC} not found")

    raw = SRC.read_bytes()
    # mtime=0 so the output is byte-identical for identical input, which keeps
    # rebuilds from churning just because the clock moved on.
    packed = gzip.compress(raw, compresslevel=9, mtime=0)

    _check_startup()

    body = ",".join(f"0x{b:02x}" for b in packed)
    text = (
        "/* Generated by tools/gen_ui_asset.py from www/index.html -- do not edit. */\n"
        f"const unsigned char ui_index_html_gz[] = {{{body}}};\n"
        f"const unsigned int ui_index_html_gz_len = {len(packed)};\n"
    )

    # Only rewrite when the content really changed, so ninja does not relink on
    # every single build.
    if OUT.is_file() and OUT.read_text() == text:
        print(f"gen_ui_asset: unchanged ({len(raw)} -> {len(packed)} bytes)")
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"gen_ui_asset: {SRC.name} {len(raw)} -> {len(packed)} bytes gzip")


def _check_startup():
    """Refuse to embed an interface that cannot start.

    A variable declared below the code that reads it throws before anything
    renders, so the page comes up blank -- with the failure visible only in a
    console nobody has open, and often only on one #hash, so the other entry
    points keep working and hide it. That has happened twice here.

    Skipped rather than fatal when node is missing: a toolchain without it
    should still be able to build firmware.
    """
    checker = ROOT / "tools" / "check_ui.js"
    if not checker.is_file():
        return
    if shutil.which("node") is None:
        print("gen_ui_asset: node not found, skipping the startup check")
        return

    result = subprocess.run(["node", str(checker), str(SRC)],
                            capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit(result.stderr.strip() or "gen_ui_asset: the interface fails to start")
    # Printed so a passing check is visible too -- a guard nobody sees run is a
    # guard nobody trusts.
    print(result.stderr.strip())


generate()
